### ISSUE TITLE
MEGATHREAD: Features and known bugs

### ISSUE THREAD

**Issue by josh-abad** [josh-abad/proctor-vue-web#2]
1. [x] Responsive on mobile
2. [x] Face detection & recognition
3. [ ] [~~Chrome extension to track tabs~~](https://github.com/josh-abad/proctor-vue-extension)
4. [x] Links to external sites (e.g., Zoom meetings, PDF files)~~ or file uploads in course~~. bfaccd79f4b0cb88acc01348bf5f7db4798f4a54

## Administrator

1. [x] Create Course
2. [x] Add Student
3. [ ] ~~Add Coordinator~~

## Coordinator

1. [x] Create Exam
   - [x] Text
   - [x] Multiple Choice
   - [x] Checkbox
2. [x] Edit Exam ee7428f62cdd41317a72b1fabb8101b8bdb55fef
3. [x] Delete Exam
4. [x] Overview Tab
5. [x] Students Tab
   - [x] can search students
   - [x] can add student
6. [x] Grades (show formula?)

## Student

1. [x] Take Exam
2. [x] View Calendar
3. [x] View Grades
4. [x] Disable Student Tab
5. [ ] ~~Restrict upload Face ID or coordinator will upload the reference image~~

# Suggestions

### Students

- ~~Disable students section in the course~~

### Coordinator

- ~~Edit course~~
- ~~View students' answers~~
- ~~Create post (Zoom links or other links and file upload)~~ bfaccd79f4b0cb88acc01348bf5f7db4798f4a54
- ~~Fix Student Tab~~ 521a3c533651024ffce0816548dc121a926b418e

  a. ~~Add student~~

### Exams

- ~~Optional case sensitive text answer~~ 041e82641ee0d96b

## From Rhycca

1. [x] Display message when exam ends due to exceeded warnings. 04af7d1dd9565033b2780dce502448bfdf00051f
2. [x] Hide other students' information from students.
3. [x] Persist warnings on refresh. 00be2cac5669e83d026476d40f6204068a7a22c1
4. [x] Warnings sometimes go over the maximum (5) without ending the exam. 64b2fe7e3377c6ef6f68c9a11a55dd1d3b6f2776
5. [x] Answers to exam questions can be viewed in API response.
6. [ ] ~~Users can upload an image of someone other than themselves.~~
7. [x] Keep track of exam items that the user has answered. fa60cf22fa8f775577096e24b71761ed42721378
8. [ ] ~~Limit uploading of reference image (every few months or so).~~
9. [x] Display a banner for first-time users to upload a reference image. 9402be73b8384f82b8da32c65cfc33e54bbef2ce
10. [x] Reference image sometimes doesn't upload even if image is valid (also sometimes it uploads but the new url doesn't get saved to the database.

**Comment by greeklx** [comment]
Suggestion:
- [x] Add Calendar support (GCalendar, Outlook)
- [x] Create post (Zoom links or other links and file upload) bfaccd79f4b0cb88acc01348bf5f7db4798f4a54
- [x] Student logs 
- [x] Create Exam function - Add Essay

**Comment by greeklx** [comment]
## [Revision:](https://docs.google.com/document/d/1Vnac_I_IxUzoNEofNFROTDJa3FmPetW7u4jmLSz3Cb8/)

Sir Zurbano,  Mr. Earl ,  Mr. George
 - [x] #6 
 - [x] #9 
 - [x] Exam Shuffle Questions
 - [x] #7
 - [x] #10 
 - [ ] #8

**Comment by josh-abad** [comment]
> Warnings should be on the top .
I-veto ko 'to. Hard disagree ako kay sir about sa placement ng warnings. Sa bottom nga, pero fixed siya so visible siya sa screen palagi. Kapag fixed na nasa taas naman ng main panel (1), matatakpan 'yung questions. Kung nasa top-right (2), mukhang hindi na siya fixed at kailangan pa mag scroll sa taas para makita ng user. Kapag sa taas ng exam navigation (3), since hindi fixed ang position ng exam navigation, magiging hindi rin fixed 'yung warning panel.
